Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase

[xml]$xaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="CallBridge Softphone" Width="1080" Height="720" MinWidth="920" MinHeight="620" WindowStartupLocation="CenterScreen" Background="#090E15" Foreground="#E9E7E2" FontFamily="Segoe UI">
  <Window.Resources>
    <SolidColorBrush x:Key="Panel" Color="#141D28"/><SolidColorBrush x:Key="Panel2" Color="#101822"/><SolidColorBrush x:Key="Line" Color="#27313D"/><SolidColorBrush x:Key="Gold" Color="#C8AA72"/><SolidColorBrush x:Key="Muted" Color="#82909F"/>
    <Style TargetType="Button"><Setter Property="Foreground" Value="#D8DDE2"/><Setter Property="Background" Value="Transparent"/><Setter Property="BorderBrush" Value="#27313D"/><Setter Property="BorderThickness" Value="1"/><Setter Property="Padding" Value="12,9"/><Setter Property="Cursor" Value="Hand"/><Setter Property="Template"><Setter.Value><ControlTemplate TargetType="Button"><Border x:Name="B" Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" CornerRadius="8" Padding="{TemplateBinding Padding}"><ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/></Border><ControlTemplate.Triggers><Trigger Property="IsMouseOver" Value="True"><Setter TargetName="B" Property="BorderBrush" Value="#806D4A"/><Setter TargetName="B" Property="Background" Value="#151D25"/></Trigger><Trigger Property="IsEnabled" Value="False"><Setter Property="Opacity" Value=".35"/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
    <Style x:Key="Nav" TargetType="Button" BasedOn="{StaticResource {x:Type Button}}"><Setter Property="HorizontalContentAlignment" Value="Left"/><Setter Property="BorderThickness" Value="0"/><Setter Property="Padding" Value="16,12"/><Setter Property="Margin" Value="0,2"/></Style>
    <Style x:Key="Dial" TargetType="Button" BasedOn="{StaticResource {x:Type Button}}"><Setter Property="Width" Value="68"/><Setter Property="Height" Value="58"/><Setter Property="Margin" Value="5"/><Setter Property="FontSize" Value="18"/><Setter Property="Background" Value="#17212D"/></Style>
    <Style TargetType="TextBox"><Setter Property="Foreground" Value="#F0EEE9"/><Setter Property="Background" Value="#0C131C"/><Setter Property="BorderBrush" Value="#27313D"/><Setter Property="Padding" Value="12"/><Setter Property="CaretBrush" Value="#C8AA72"/></Style>
  </Window.Resources>
  <Grid><Grid.ColumnDefinitions><ColumnDefinition Width="220"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions>
    <Border Grid.Column="0" Background="#0B1119" BorderBrush="#302A21" BorderThickness="0,0,1,0"><Grid Margin="18"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
      <StackPanel Orientation="Horizontal" Margin="4,8,4,28"><Border Width="38" Height="38" CornerRadius="11" BorderBrush="#806D4A" BorderThickness="1" Background="#211D17"><TextBlock Text="â–¥" Foreground="#D4B87F" FontSize="21" HorizontalAlignment="Center" VerticalAlignment="Center"/></Border><StackPanel Margin="11,1,0,0"><TextBlock Text="CALLBRIDGE" FontSize="12" FontWeight="Bold"/><TextBlock Text="HIVE SOFTPHONE" Foreground="#6F7B88" FontSize="9" Margin="0,4,0,0"/></StackPanel></StackPanel>
      <Border Grid.Row="1" Background="#121B25" BorderBrush="#27313D" BorderThickness="1" CornerRadius="9" Padding="11" Margin="0,0,0,18"><StackPanel Orientation="Horizontal"><Ellipse Width="9" Height="9" Fill="#6FC29D" Margin="0,3,9,0"/><StackPanel><TextBlock Text="Available" Foreground="#A5D7C0" FontSize="11" FontWeight="SemiBold"/><TextBlock Text="Extension 201" Foreground="#667584" FontSize="9"/></StackPanel></StackPanel></Border>
      <StackPanel Grid.Row="2"><Button Name="NavPhone" Style="{StaticResource Nav}" Content="â˜Ž   Phone" Foreground="#E8D8B7" Background="#1B1B19" BorderBrush="#8A7147" BorderThickness="2,0,0,0"/><Button Name="NavContacts" Style="{StaticResource Nav}" Content="â™™   Contacts"/><Button Name="NavHistory" Style="{StaticResource Nav}" Content="â—·   Call history"/><Button Name="NavMessages" Style="{StaticResource Nav}" Content="âœ‰   Messages"/><Button Name="NavVoicemail" Style="{StaticResource Nav}" Content="â—‰   Voicemail"/><Button Name="NavSettings" Style="{StaticResource Nav}" Content="âš™   Settings"/></StackPanel>
      <StackPanel Grid.Row="3" Margin="5,0,5,8"><TextBlock Text="PBX STATUS" Foreground="#626F7D" FontSize="8"/><StackPanel Orientation="Horizontal" Margin="0,9,0,0"><Ellipse Name="StatusDot" Width="8" Height="8" Fill="#D6AF6E" Margin="0,3,8,0"/><TextBlock Name="RegistrationText" Text="Not registered" Foreground="#A78F69" FontSize="10"/></StackPanel><TextBlock Text="CallBridge v0.1.0" Foreground="#4E5965" FontSize="9" Margin="0,18,0,0"/></StackPanel>
    </Grid></Border>
    <Grid Grid.Column="1"><Grid.RowDefinitions><RowDefinition Height="64"/><RowDefinition Height="*"/></Grid.RowDefinitions>
      <Border BorderBrush="#202A35" BorderThickness="0,0,0,1" Background="#0B1119"><Grid Margin="28,0"><TextBlock Name="PageTitle" Text="Phone" FontSize="14" FontWeight="SemiBold" VerticalAlignment="Center"/><StackPanel Orientation="Horizontal" HorizontalAlignment="Right" VerticalAlignment="Center"><Button Name="TopMode" Content="Available  â–¾" Padding="12,7"/><Border Width="32" Height="32" CornerRadius="16" Background="#283340" Margin="12,0,0,0"><TextBlock Text="IT" FontSize="10" FontWeight="Bold" HorizontalAlignment="Center" VerticalAlignment="Center"/></Border></StackPanel></Grid></Border>
      <Grid Grid.Row="1" Margin="30"><Grid Name="PhonePage"><Grid.ColumnDefinitions><ColumnDefinition Width="340"/><ColumnDefinition Width="18"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions>
        <Border Grid.Column="0" Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="25"><Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><TextBlock Name="CallStatus" Text="READY TO CALL" Foreground="#73808D" FontSize="9" HorizontalAlignment="Center"/><TextBox Name="NumberBox" Grid.Row="1" TextAlignment="Center" FontSize="21" Margin="0,14,0,18" BorderThickness="0,0,0,1" ToolTip="Enter name or number"/><UniformGrid Name="DialPad" Grid.Row="2" Columns="3" HorizontalAlignment="Center" VerticalAlignment="Center"><Button Style="{StaticResource Dial}" Content="1"/><Button Style="{StaticResource Dial}" Content="2  ABC"/><Button Style="{StaticResource Dial}" Content="3  DEF"/><Button Style="{StaticResource Dial}" Content="4  GHI"/><Button Style="{StaticResource Dial}" Content="5  JKL"/><Button Style="{StaticResource Dial}" Content="6  MNO"/><Button Style="{StaticResource Dial}" Content="7  PQRS"/><Button Style="{StaticResource Dial}" Content="8  TUV"/><Button Style="{StaticResource Dial}" Content="9  WXYZ"/><Button Style="{StaticResource Dial}" Content="*"/><Button Style="{StaticResource Dial}" Content="0  +"/><Button Style="{StaticResource Dial}" Content="#"/></UniformGrid><Button Name="CallButton" Grid.Row="3" Content="â˜Ž   CALL" Margin="0,20,0,0" Padding="15" FontWeight="Bold" Foreground="#111711" Background="#70BE99" BorderThickness="0"/></Grid></Border>
        <StackPanel Grid.Column="2"><Border Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="24"><StackPanel><TextBlock Text="FAVORITES" Foreground="#73808D" FontSize="9"/><Grid Margin="0,18,0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Maria Jensen" FontWeight="SemiBold"/><TextBlock Text="Simi Valley Dental Group Â· Mobile" Foreground="{StaticResource Muted}" FontSize="10" Margin="0,4,0,0"/></StackPanel><Button Grid.Column="1" Name="FavoriteCall" Content="â˜Ž" Width="36" Height="34" Padding="0" Foreground="#9CD5B9"/></Grid><Separator Background="#27313D"/><Grid Margin="0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Daniel Kim" FontWeight="SemiBold"/><TextBlock Text="West Coast Manufacturing Â· Work" Foreground="{StaticResource Muted}" FontSize="10" Margin="0,4,0,0"/></StackPanel><Button Grid.Column="1" Content="â˜Ž" Width="36" Height="34" Padding="0" Foreground="#9CD5B9"/></Grid></StackPanel></Border>
          <Border Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="24" Margin="0,18,0,0"><StackPanel><DockPanel><TextBlock Text="RECENT CALLS" Foreground="#73808D" FontSize="9"/><TextBlock Text="View all" Foreground="#B99E6A" FontSize="9" HorizontalAlignment="Right"/></DockPanel><Grid Margin="0,18,0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="32"/><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBlock Text="â†™" Foreground="#71C29E" FontSize="17"/><StackPanel Grid.Column="1"><TextBlock Text="Simi Valley Dental Group" FontWeight="SemiBold" FontSize="11"/><TextBlock Text="Today, 3:42 PM Â· 04:18" Foreground="{StaticResource Muted}" FontSize="9"/></StackPanel><Button Grid.Column="2" Content="â˜Ž" Width="34" Padding="0"/></Grid><Separator Background="#27313D"/><Grid Margin="0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="32"/><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBlock Text="â†™" Foreground="#D87889" FontSize="17"/><StackPanel Grid.Column="1"><TextBlock Text="West Coast Manufacturing" FontWeight="SemiBold" FontSize="11"/><TextBlock Text="Today, 2:16 PM Â· Missed" Foreground="#B77582" FontSize="9"/></StackPanel><Button Grid.Column="2" Content="â˜Ž" Width="34" Padding="0"/></Grid></StackPanel></Border>
        </StackPanel>
      </Grid>
      <Grid Name="ListPage" Visibility="Collapsed"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="18"/><RowDefinition Height="*"/></Grid.RowDefinitions><DockPanel><StackPanel><TextBlock Name="ListHeading" Text="Contacts" FontSize="30" FontWeight="SemiBold"/><TextBlock Name="ListSubheading" Text="People and extensions in your organization" Foreground="{StaticResource Muted}" Margin="0,7,0,0"/></StackPanel><TextBox Width="260" Height="38" HorizontalAlignment="Right" VerticalAlignment="Center" Text="Search" Foreground="#788593"/></DockPanel><Border Grid.Row="2" Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="22"><StackPanel Name="ListContent"/></Border></Grid>
      </Grid>
    </Grid>
  </Grid>
</Window>
'@

$reader = New-Object System.Xml.XmlNodeReader $xaml
$window = [Windows.Markup.XamlReader]::Load($reader)
function C($name) { $window.FindName($name) }
$phonePage=C 'PhonePage'; $listPage=C 'ListPage'; $pageTitle=C 'PageTitle'; $heading=C 'ListHeading'; $subheading=C 'ListSubheading'; $content=C 'ListContent'; $number=C 'NumberBox'; $callButton=C 'CallButton'; $callStatus=C 'CallStatus'

function Show-List($title,$subtitle,$rows) {
  $phonePage.Visibility='Collapsed'; $listPage.Visibility='Visible'; $pageTitle.Text=$title; $heading.Text=$title; $subheading.Text=$subtitle; $content.Children.Clear()
  foreach($row in $rows){$b=New-Object Windows.Controls.Border;$b.BorderBrush='#27313D';$b.BorderThickness='0,0,0,1';$b.Padding='8,16';$g=New-Object Windows.Controls.Grid;$t=New-Object Windows.Controls.TextBlock;$t.Text=$row;$t.FontSize=12;$t.Foreground='#DCE1E6';$g.Children.Add($t)|Out-Null;$b.Child=$g;$content.Children.Add($b)|Out-Null}
}
function Show-Phone { $phonePage.Visibility='Visible';$listPage.Visibility='Collapsed';$pageTitle.Text='Phone' }
(C 'NavPhone').Add_Click({Show-Phone})
(C 'NavContacts').Add_Click({Show-List 'Contacts' 'People and extensions in your organization' @('Maria Jensen     Available     (805) 555-0147','Daniel Kim     In a call     (818) 555-0192','Front Office     Available     Extension 200','Support Queue     2 agents available     Extension 600')})
(C 'NavHistory').Add_Click({Show-List 'Call history' 'Inbound, outbound, and missed calls' @('Inbound Â· Simi Valley Dental Group Â· Today 3:42 PM Â· 04:18','Missed Â· West Coast Manufacturing Â· Today 2:16 PM','Outbound Â· Northstar Property Management Â· Today 11:08 AM Â· 12:06','Inbound Â· Unknown caller Â· Yesterday 4:54 PM Â· 01:44')})
(C 'NavMessages').Add_Click({Show-List 'Messages' 'Team conversations and SMS' @('Maria Jensen Â· Can you call me when available? Â· 2 min','Support Team Â· Queue coverage updated Â· 18 min','Daniel Kim Â· Thank you for the quick help Â· 1 hr')})
(C 'NavVoicemail').Add_Click({Show-List 'Voicemail' 'New and saved voice messages' @('New Â· (805) 555-0122 Â· Today 1:08 PM Â· 00:42','Saved Â· Simi Valley Dental Group Â· Yesterday Â· 01:14')})
(C 'NavSettings').Add_Click({Show-List 'Settings' 'SIP account, audio, and calling preferences' @('SIP account Â· Not configured','Microphone Â· Windows default device','Speaker Â· Windows default device','Ringtone Â· CallBridge Classic','Launch at Windows startup Â· Off','Keep window on top during calls Â· On')})

foreach($button in (C 'DialPad').Children){$button.Add_Click({param($s,$e);$digit=[string]$s.Content;$number.Text += $digit.Substring(0,1)})}
(C 'FavoriteCall').Add_Click({$number.Text='(805) 555-0147';$callButton.RaiseEvent((New-Object Windows.RoutedEventArgs([Windows.Controls.Button]::ClickEvent)))})
$callButton.Add_Click({
  if([string]::IsNullOrWhiteSpace($number.Text)){return}
  if($callButton.Content -like '*END*'){$callStatus.Text='READY TO CALL';$callButton.Content='â˜Ž   CALL';$callButton.Background='#70BE99';$number.IsReadOnly=$false}
  else{$callStatus.Text='CALLING Â· SIMULATED';$callButton.Content='â–    END CALL';$callButton.Background='#C95669';$number.IsReadOnly=$true}
})
$window.ShowDialog() | Out-Null

