Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase

$settingsPath=Join-Path $PSScriptRoot 'settings.json'
Add-Type -AssemblyName Microsoft.VisualBasic
$appSettings=if(Test-Path $settingsPath){Get-Content -Raw $settingsPath|ConvertFrom-Json}else{[pscustomobject]@{apiBase='http://127.0.0.1:8787';extension='201';displayName='IT Health Technologies';simulateCalls=$true}}

[xml]$xaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="CallBridge Softphone" Width="1080" Height="720" MinWidth="920" MinHeight="620" WindowStartupLocation="CenterScreen" Background="#090E15" Foreground="#E9E7E2" FontFamily="Segoe UI">
  <Window.Resources>
    <SolidColorBrush x:Key="Panel" Color="#141D28"/><SolidColorBrush x:Key="Panel2" Color="#101822"/><SolidColorBrush x:Key="Line" Color="#27313D"/><SolidColorBrush x:Key="Gold" Color="#26A7DF"/><SolidColorBrush x:Key="Muted" Color="#82909F"/>
    <Style TargetType="Button"><Setter Property="Foreground" Value="#D8DDE2"/><Setter Property="Background" Value="Transparent"/><Setter Property="BorderBrush" Value="#27313D"/><Setter Property="BorderThickness" Value="1"/><Setter Property="Padding" Value="12,9"/><Setter Property="Cursor" Value="Hand"/><Setter Property="Template"><Setter.Value><ControlTemplate TargetType="Button"><Border x:Name="B" Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" CornerRadius="8" Padding="{TemplateBinding Padding}"><ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/></Border><ControlTemplate.Triggers><Trigger Property="IsMouseOver" Value="True"><Setter TargetName="B" Property="BorderBrush" Value="#1F78A8"/><Setter TargetName="B" Property="Background" Value="#151D25"/></Trigger><Trigger Property="IsEnabled" Value="False"><Setter Property="Opacity" Value=".35"/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
    <Style x:Key="Nav" TargetType="Button" BasedOn="{StaticResource {x:Type Button}}"><Setter Property="HorizontalContentAlignment" Value="Left"/><Setter Property="BorderThickness" Value="0"/><Setter Property="Padding" Value="16,12"/><Setter Property="Margin" Value="0,2"/></Style>
    <Style x:Key="Dial" TargetType="Button" BasedOn="{StaticResource {x:Type Button}}"><Setter Property="Width" Value="68"/><Setter Property="Height" Value="58"/><Setter Property="Margin" Value="5"/><Setter Property="FontSize" Value="18"/><Setter Property="Background" Value="#17212D"/></Style>
    <Style TargetType="TextBox"><Setter Property="Foreground" Value="#F0EEE9"/><Setter Property="Background" Value="#0C131C"/><Setter Property="BorderBrush" Value="#27313D"/><Setter Property="Padding" Value="12"/><Setter Property="CaretBrush" Value="#26A7DF"/></Style>
  </Window.Resources>
  <Grid><Grid.ColumnDefinitions><ColumnDefinition Width="220"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions>
    <Border Grid.Column="0" Background="#0B1119" BorderBrush="#163B54" BorderThickness="0,0,1,0"><Grid Margin="18"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
      <StackPanel Orientation="Horizontal" Margin="4,8,4,28"><Border Width="38" Height="38" CornerRadius="11" BorderBrush="#1F78A8" BorderThickness="1" Background="#10293A"><TextBlock Name="LogoIcon" Text="CB" Foreground="#45C4B1" FontSize="12" FontWeight="Bold" HorizontalAlignment="Center" VerticalAlignment="Center"/></Border><StackPanel Margin="11,1,0,0"><TextBlock Name="BrandTitle" Text="CALLBRIDGE" FontSize="12" FontWeight="Bold"/><TextBlock Name="BrandSubtitle" Text="IT HEALTH TECHNOLOGIES" Foreground="#6F7B88" FontSize="8" Margin="0,4,0,0"/></StackPanel></StackPanel>
      <Border Grid.Row="1" Background="#121B25" BorderBrush="#27313D" BorderThickness="1" CornerRadius="9" Padding="11" Margin="0,0,0,18"><StackPanel Orientation="Horizontal"><Ellipse Width="9" Height="9" Fill="#6FC29D" Margin="0,3,9,0"/><StackPanel><TextBlock Text="Available" Foreground="#A5D7C0" FontSize="11" FontWeight="SemiBold"/><TextBlock Text="Extension 201" Foreground="#667584" FontSize="9"/></StackPanel></StackPanel></Border>
      <StackPanel Grid.Row="2"><Button Name="NavDashboard" Style="{StaticResource Nav}" Content="Dashboard"/><Button Name="NavPhone" Style="{StaticResource Nav}" Content="Phone" Foreground="#EAF7FC" Background="#10283A" BorderBrush="#26A7DF" BorderThickness="2,0,0,0"/><Button Name="NavContacts" Style="{StaticResource Nav}" Content="Contacts"/><Button Name="NavHistory" Style="{StaticResource Nav}" Content="Call history"/><Button Name="NavMessages" Style="{StaticResource Nav}" Content="Messages"/><Button Name="NavVoicemail" Style="{StaticResource Nav}" Content="Voicemail"/><Button Name="NavIntegrations" Style="{StaticResource Nav}" Content="Connections"/><Button Name="NavSettings" Style="{StaticResource Nav}" Content="Settings"/></StackPanel>
      <StackPanel Grid.Row="3" Margin="5,0,5,8"><TextBlock Text="CONNECTOR STATUS" Foreground="#626F7D" FontSize="8"/><StackPanel Orientation="Horizontal" Margin="0,9,0,0"><Ellipse Name="StatusDot" Width="8" Height="8" Fill="#F2B84B" Margin="0,3,8,0"/><TextBlock Name="RegistrationText" Text="Checking service" Foreground="#A6B5C3" FontSize="10"/></StackPanel><TextBlock Text="CallBridge v0.5.0" Foreground="#4E5965" FontSize="9" Margin="0,18,0,0"/></StackPanel>
    </Grid></Border>
    <Grid Grid.Column="1"><Grid.RowDefinitions><RowDefinition Height="64"/><RowDefinition Height="*"/></Grid.RowDefinitions>
      <Border BorderBrush="#202A35" BorderThickness="0,0,0,1" Background="#0B1119"><Grid Margin="28,0"><TextBlock Name="PageTitle" Text="Phone" FontSize="14" FontWeight="SemiBold" VerticalAlignment="Center"/><StackPanel Orientation="Horizontal" HorizontalAlignment="Right" VerticalAlignment="Center"><Button Name="TopMode" Content="Available  " Padding="12,7"/><Border Width="32" Height="32" CornerRadius="16" Background="#283340" Margin="12,0,0,0"><TextBlock Text="IT" FontSize="10" FontWeight="Bold" HorizontalAlignment="Center" VerticalAlignment="Center"/></Border></StackPanel></Grid></Border>
      <Grid Grid.Row="1" Margin="30"><Grid Name="PhonePage"><Grid.ColumnDefinitions><ColumnDefinition Width="340"/><ColumnDefinition Width="18"/><ColumnDefinition Width="*"/></Grid.ColumnDefinitions>
        <Border Grid.Column="0" Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="25"><Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><TextBlock Name="CallStatus" Text="READY TO CALL" Foreground="#73808D" FontSize="9" HorizontalAlignment="Center"/><TextBox Name="NumberBox" Grid.Row="1" TextAlignment="Center" FontSize="21" Margin="0,14,0,18" BorderThickness="0,0,0,1" ToolTip="Enter name or number"/><UniformGrid Name="DialPad" Grid.Row="2" Columns="3" HorizontalAlignment="Center" VerticalAlignment="Center"><Button Style="{StaticResource Dial}" Content="1"/><Button Style="{StaticResource Dial}" Content="2  ABC"/><Button Style="{StaticResource Dial}" Content="3  DEF"/><Button Style="{StaticResource Dial}" Content="4  GHI"/><Button Style="{StaticResource Dial}" Content="5  JKL"/><Button Style="{StaticResource Dial}" Content="6  MNO"/><Button Style="{StaticResource Dial}" Content="7  PQRS"/><Button Style="{StaticResource Dial}" Content="8  TUV"/><Button Style="{StaticResource Dial}" Content="9  WXYZ"/><Button Style="{StaticResource Dial}" Content="*"/><Button Style="{StaticResource Dial}" Content="0  +"/><Button Style="{StaticResource Dial}" Content="#"/></UniformGrid><Button Name="CallButton" Grid.Row="3" Content="CALL" Margin="0,20,0,0" Padding="15" FontWeight="Bold" Foreground="#111711" Background="#39C292" BorderThickness="0"/><UniformGrid Name="ActiveControls" Grid.Row="4" Columns="3" Visibility="Collapsed" Margin="0,10,0,0"><Button Name="MuteButton" Content="Mute" Margin="2" Padding="7"/><Button Name="HoldButton" Content="Hold" Margin="2" Padding="7"/><Button Name="TransferButton" Content="Transfer" Margin="2" Padding="7"/></UniformGrid></Grid></Border>
        <StackPanel Grid.Column="2"><Border Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="24"><StackPanel><TextBlock Text="FAVORITES" Foreground="#73808D" FontSize="9"/><Grid Margin="0,18,0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Maria Jensen" FontWeight="SemiBold"/><TextBlock Text="Simi Valley Dental Group  Mobile" Foreground="{StaticResource Muted}" FontSize="10" Margin="0,4,0,0"/></StackPanel><Button Grid.Column="1" Name="FavoriteCall" Content="" Width="36" Height="34" Padding="0" Foreground="#6ED7B0"/></Grid><Separator Background="#27313D"/><Grid Margin="0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="Daniel Kim" FontWeight="SemiBold"/><TextBlock Text="West Coast Manufacturing  Work" Foreground="{StaticResource Muted}" FontSize="10" Margin="0,4,0,0"/></StackPanel><Button Grid.Column="1" Content="" Width="36" Height="34" Padding="0" Foreground="#6ED7B0"/></Grid></StackPanel></Border>
          <Border Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="24" Margin="0,18,0,0"><StackPanel><DockPanel><TextBlock Text="RECENT CALLS" Foreground="#73808D" FontSize="9"/><TextBlock Text="View all" Foreground="#35B5C4" FontSize="9" HorizontalAlignment="Right"/></DockPanel><Grid Margin="0,18,0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="32"/><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBlock Text="" Foreground="#71C29E" FontSize="17"/><StackPanel Grid.Column="1"><TextBlock Text="Simi Valley Dental Group" FontWeight="SemiBold" FontSize="11"/><TextBlock Text="Today, 3:42 PM  04:18" Foreground="{StaticResource Muted}" FontSize="9"/></StackPanel><Button Grid.Column="2" Content="" Width="34" Padding="0"/></Grid><Separator Background="#27313D"/><Grid Margin="0,12"><Grid.ColumnDefinitions><ColumnDefinition Width="32"/><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBlock Text="" Foreground="#D87889" FontSize="17"/><StackPanel Grid.Column="1"><TextBlock Text="West Coast Manufacturing" FontWeight="SemiBold" FontSize="11"/><TextBlock Text="Today, 2:16 PM  Missed" Foreground="#B77582" FontSize="9"/></StackPanel><Button Grid.Column="2" Content="" Width="34" Padding="0"/></Grid></StackPanel></Border>
        </StackPanel>
      </Grid>
      <Grid Name="ListPage" Visibility="Collapsed"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="18"/><RowDefinition Height="*"/></Grid.RowDefinitions><DockPanel><StackPanel><TextBlock Name="ListHeading" Text="Contacts" FontSize="30" FontWeight="SemiBold"/><TextBlock Name="ListSubheading" Text="People and extensions in your organization" Foreground="{StaticResource Muted}" Margin="0,7,0,0"/></StackPanel><TextBox Name="SearchBox" Width="260" Height="38" HorizontalAlignment="Right" VerticalAlignment="Center" Text="" ToolTip="Search this view" Foreground="#DCE6EC"/></DockPanel><Border Grid.Row="2" Background="{StaticResource Panel}" BorderBrush="{StaticResource Line}" BorderThickness="1" CornerRadius="13" Padding="22"><ScrollViewer VerticalScrollBarVisibility="Auto"><StackPanel Name="ListContent"/></ScrollViewer></Border></Grid>
      </Grid>
    </Grid>
  </Grid>
</Window>
'@

$reader = New-Object System.Xml.XmlNodeReader $xaml
$window = [Windows.Markup.XamlReader]::Load($reader)
function C($name) { $window.FindName($name) }
$window.Title="$($appSettings.productName) - $($appSettings.companyName)";(C 'BrandTitle').Text=$appSettings.productName.ToUpper();(C 'BrandSubtitle').Text=$appSettings.companyName.ToUpper();(C 'LogoIcon').Text=($appSettings.productName.Substring(0,[Math]::Min(2,$appSettings.productName.Length))).ToUpper()
$window.Topmost=$false
$phonePage=C 'PhonePage'; $listPage=C 'ListPage'; $pageTitle=C 'PageTitle'; $heading=C 'ListHeading'; $subheading=C 'ListSubheading'; $content=C 'ListContent'; $number=C 'NumberBox'; $callButton=C 'CallButton'; $callStatus=C 'CallStatus'; $search=C 'SearchBox'
$script:currentRows=@(); $script:callSeconds=0; $script:activeCallId=$null; $script:muted=$false; $script:held=$false
function Get-Api($path){try{return Invoke-RestMethod -Uri ($appSettings.apiBase.TrimEnd('/')+$path) -Method Get -TimeoutSec 2}catch{return $null}}
function Post-Api($path,$payload=@{}){try{return Invoke-RestMethod -Uri ($appSettings.apiBase.TrimEnd('/')+$path) -Method Post -ContentType 'application/json' -Body ($payload|ConvertTo-Json -Compress) -TimeoutSec 3}catch{return $null}}
function Refresh-Connection{$health=Get-Api '/health';$dot=C 'StatusDot';$label=C 'RegistrationText';if($health -and $health.ok){$dot.Fill='#39C292';$label.Text="Connector online v$($health.version)";$label.Foreground='#74D5AE'}else{$dot.Fill='#F2B84B';$label.Text='Connector offline';$label.Foreground='#A6B5C3'}}

function Set-NavIcon($name,$glyph,$label){
  $button=C $name; $panel=New-Object Windows.Controls.StackPanel; $panel.Orientation='Horizontal'
  $icon=New-Object Windows.Controls.TextBlock; $icon.FontFamily='Segoe MDL2 Assets'; $icon.Text=[char]$glyph; $icon.FontSize=15; $icon.Width=29; $icon.Foreground='#62C9D1'
  $text=New-Object Windows.Controls.TextBlock; $text.Text=$label; $text.FontSize=11; $text.VerticalAlignment='Center'
  $panel.Children.Add($icon)|Out-Null; $panel.Children.Add($text)|Out-Null; $button.Content=$panel
}
Set-NavIcon 'NavDashboard' 0xE80F 'Dashboard'; Set-NavIcon 'NavPhone' 0xE717 'Phone'; Set-NavIcon 'NavContacts' 0xE77B 'Contacts'; Set-NavIcon 'NavHistory' 0xE81C 'Call history'; Set-NavIcon 'NavMessages' 0xE8BD 'Messages'; Set-NavIcon 'NavVoicemail' 0xE720 'Voicemail'; Set-NavIcon 'NavIntegrations' 0xE774 'Connections'; Set-NavIcon 'NavSettings' 0xE713 'Settings'
(C 'FavoriteCall').Content=[char]0xE717; (C 'FavoriteCall').FontFamily='Segoe MDL2 Assets'; $callButton.Content='CALL'

function Render-Rows($rows){
  $content.Children.Clear()
  foreach($row in $rows){
    $parts=$row -split '\|'; $card=New-Object Windows.Controls.Border; $card.BorderBrush='#273746'; $card.BorderThickness='0,0,0,1'; $card.Padding='10,15'
    $grid=New-Object Windows.Controls.Grid; $grid.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='42'})); $grid.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='*'})); $grid.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='Auto'}))
    $badge=New-Object Windows.Controls.Border; $badge.Width=32;$badge.Height=32;$badge.CornerRadius=8;$badge.Background='#102D3D';$badge.BorderBrush='#1E607E';$badge.BorderThickness=1
    $ico=New-Object Windows.Controls.TextBlock;$ico.FontFamily='Segoe MDL2 Assets';$ico.Text=[char]0xE717;$ico.Foreground='#45C4B1';$ico.HorizontalAlignment='Center';$ico.VerticalAlignment='Center';$badge.Child=$ico
    $stack=New-Object Windows.Controls.StackPanel;[Windows.Controls.Grid]::SetColumn($stack,1);$title=New-Object Windows.Controls.TextBlock;$title.Text=$parts[0];$title.FontWeight='SemiBold';$title.FontSize=12;$title.Foreground='#E7EFF3';$meta=New-Object Windows.Controls.TextBlock;$meta.Text=$parts[1];$meta.Margin='0,4,0,0';$meta.FontSize=9;$meta.Foreground='#7F92A1';$stack.Children.Add($title)|Out-Null;$stack.Children.Add($meta)|Out-Null
    $action=New-Object Windows.Controls.Button;[Windows.Controls.Grid]::SetColumn($action,2);$action.Content=if($parts.Count -gt 2){$parts[2]}else{'Open'};$action.Padding='12,7';$action.FontSize=9;$action.Tag=$parts
    if($parts[1] -match '\([0-9]{3}\)|Extension'){$action.Content='Call';$action.Add_Click({param($s,$e);$p=$s.Tag;$number.Text=($p[1] -replace '^.*?((\([0-9]{3}\).*?)|Extension.*)$','$1');Show-Phone})}
    $grid.Children.Add($badge)|Out-Null;$grid.Children.Add($stack)|Out-Null;$grid.Children.Add($action)|Out-Null;$card.Child=$grid;$content.Children.Add($card)|Out-Null
  }
}
function Show-List($title,$subtitle,$rows) {$script:currentRows=$rows;$phonePage.Visibility='Collapsed';$listPage.Visibility='Visible';$pageTitle.Text=$title;$heading.Text=$title;$subheading.Text=$subtitle;$search.Visibility='Visible';$search.Text='';Render-Rows $rows}
function Show-Phone {$phonePage.Visibility='Visible';$listPage.Visibility='Collapsed';$pageTitle.Text='Phone'}
function Show-Dashboard{
  $diagnostics=Get-Api '/diagnostics';$health=Get-Api '/health'
  if($diagnostics){$db=$diagnostics.database;Show-List 'Dashboard' 'Live CallBridge connector health and activity' @("Connector service|Online - version $($health.version)|Healthy","Captured calls|$($db.calls) total events - $($db.webhookCaptures) webhook captures|View","Directory|$($db.companies) companies - $($db.contacts) contacts - $($db.phones) phones|Open","Deliveries|$($db.pendingDeliveries) pending - $($db.acknowledgedDeliveries) acknowledged|Details","ASIO mode|$($diagnostics.config.asioMode) - $($diagnostics.config.host):$($diagnostics.config.port)|Configure")}
  else{Show-List 'Dashboard' 'PBX health and communications overview' @('Connector service|Offline - start CallBridge Internal on port 8787|Retry','Captured calls|Demo data - live service unavailable|View','Directory|Demo contacts loaded|Open','SIP registration|Not configured|Configure')}
}
function Show-History{
  $recent=Get-Api '/events/recent?limit=50';if($recent -and $recent.events){$rows=@($recent.events|ForEach-Object{"$($_.caller_number)|$($_.direction) - $($_.state) - $($_.occurred_at)|Call"});Show-List 'Call history' 'Live calls from the CallBridge event journal' $rows}else{Show-List 'Call history' 'Inbound, outbound, and missed calls' @('Simi Valley Dental Group|Inbound - Today 3:42 PM - 04:18|Call','West Coast Manufacturing|Missed - Today 2:16 PM - (818) 555-0192|Call','Northstar Property Management|Outbound - Today 11:08 AM - 12:06|Call')}
}
function Add-SettingField($parent,$label,$value,$password=$false){
  $wrap=New-Object Windows.Controls.StackPanel;$wrap.Margin='0,0,0,13';$caption=New-Object Windows.Controls.TextBlock;$caption.Text=$label;$caption.Foreground='#8DA0AE';$caption.FontSize=9;$caption.Margin='0,0,0,6'
  if($password){$input=New-Object Windows.Controls.PasswordBox;$input.Password=$value;$input.Foreground='#E7EFF3';$input.Background='#0C131C';$input.BorderBrush='#273746';$input.Padding=10}else{$input=New-Object Windows.Controls.TextBox;$input.Text=$value;$input.Height=37}
  $wrap.Children.Add($caption)|Out-Null;$wrap.Children.Add($input)|Out-Null;$parent.Children.Add($wrap)|Out-Null;return $input
}
function Show-Settings{
  $phonePage.Visibility='Collapsed';$listPage.Visibility='Visible';$pageTitle.Text='Settings';$heading.Text='Settings';$subheading.Text='Account, audio, application, and white-label preferences';$search.Visibility='Collapsed';$content.Children.Clear()
  $form=New-Object Windows.Controls.Grid;$form.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='*'}));$form.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='24'}));$form.ColumnDefinitions.Add((New-Object Windows.Controls.ColumnDefinition -Property @{Width='*'}))
  $left=New-Object Windows.Controls.StackPanel;$right=New-Object Windows.Controls.StackPanel;[Windows.Controls.Grid]::SetColumn($right,2)
  $h1=New-Object Windows.Controls.TextBlock;$h1.Text='PHONE ACCOUNT';$h1.Foreground='#45C4B1';$h1.FontSize=10;$h1.Margin='0,0,0,16';$left.Children.Add($h1)|Out-Null
  $api=Add-SettingField $left 'CallBridge API address' $appSettings.apiBase;$extension=Add-SettingField $left 'Extension' $appSettings.extension;$callerId=Add-SettingField $left 'Outbound caller ID' $appSettings.callerId;$sipServer=Add-SettingField $left 'SIP server / domain' $appSettings.sipServer;$sipUser=Add-SettingField $left 'SIP username' $appSettings.sipUsername
  $transportLabel=New-Object Windows.Controls.TextBlock;$transportLabel.Text='SIP transport';$transportLabel.Foreground='#8DA0AE';$transportLabel.FontSize=9;$left.Children.Add($transportLabel)|Out-Null;$transport=New-Object Windows.Controls.ComboBox;$transport.Margin='0,6,0,13';$transport.Padding=8;$transport.Background='#0C131C';$transport.Foreground='#E7EFF3';@('TLS','TCP','UDP')|ForEach-Object{$transport.Items.Add($_)|Out-Null};$transport.SelectedItem=$appSettings.sipTransport;$left.Children.Add($transport)|Out-Null
  $h2=New-Object Windows.Controls.TextBlock;$h2.Text='AUDIO AND APPLICATION';$h2.Foreground='#45C4B1';$h2.FontSize=10;$h2.Margin='0,0,0,16';$right.Children.Add($h2)|Out-Null
  $devices=@('Windows default communications device');try{$devices+=@(Get-CimInstance Win32_SoundDevice -ErrorAction Stop|Select-Object -ExpandProperty Name)}catch{}
  $micLabel=New-Object Windows.Controls.TextBlock;$micLabel.Text='Microphone';$micLabel.Foreground='#8DA0AE';$micLabel.FontSize=9;$right.Children.Add($micLabel)|Out-Null;$mic=New-Object Windows.Controls.ComboBox;$mic.Margin='0,6,0,13';$mic.Padding=8;$mic.Background='#0C131C';$mic.Foreground='#E7EFF3';$devices|Select-Object -Unique|ForEach-Object{$mic.Items.Add($_)|Out-Null};$mic.SelectedItem=$appSettings.microphone;$right.Children.Add($mic)|Out-Null
  $speakerLabel=New-Object Windows.Controls.TextBlock;$speakerLabel.Text='Speaker';$speakerLabel.Foreground='#8DA0AE';$speakerLabel.FontSize=9;$right.Children.Add($speakerLabel)|Out-Null;$speaker=New-Object Windows.Controls.ComboBox;$speaker.Margin='0,6,0,13';$speaker.Padding=8;$speaker.Background='#0C131C';$speaker.Foreground='#E7EFF3';$devices|Select-Object -Unique|ForEach-Object{$speaker.Items.Add($_)|Out-Null};$speaker.SelectedItem=$appSettings.speaker;$right.Children.Add($speaker)|Out-Null
  $product=Add-SettingField $right 'Product name' $appSettings.productName;$company=Add-SettingField $right 'Company name' $appSettings.companyName
  $startup=New-Object Windows.Controls.CheckBox;$startup.Content='Launch when I sign in to Windows';$startup.IsChecked=[bool]$appSettings.launchAtStartup;$startup.Foreground='#C9D4DB';$startup.Margin='0,7,0,13';$right.Children.Add($startup)|Out-Null
  $top=New-Object Windows.Controls.CheckBox;$top.Content='Keep window on top during calls';$top.IsChecked=[bool]$appSettings.alwaysOnTopDuringCalls;$top.Foreground='#C9D4DB';$top.Margin='0,0,0,18';$right.Children.Add($top)|Out-Null
  $status=New-Object Windows.Controls.TextBlock;$status.Foreground='#74D5AE';$status.FontSize=10;$status.Margin='0,9,0,0';$right.Children.Add($status)|Out-Null
  $buttons=New-Object Windows.Controls.StackPanel;$buttons.Orientation='Horizontal';$test=New-Object Windows.Controls.Button;$test.Content='Test connection';$test.Margin='0,0,8,0';$save=New-Object Windows.Controls.Button;$save.Content='Save settings';$save.Background='#1679A8';$save.Foreground='White';$buttons.Children.Add($test)|Out-Null;$buttons.Children.Add($save)|Out-Null;$right.Children.Add($buttons)|Out-Null
  $test.Add_Click({$old=$appSettings.apiBase;$appSettings.apiBase=$api.Text;$h=Get-Api '/health';$appSettings.apiBase=$old;$status.Text=if($h -and $h.ok){"Connected to CallBridge v$($h.version)"}else{'Connection failed - verify address and service'};$status.Foreground=if($h -and $h.ok){'#74D5AE'}else{'#E38A98'}})
  $save.Add_Click({
    $appSettings.apiBase=$api.Text.TrimEnd('/');$appSettings.extension=$extension.Text;$appSettings.callerId=$callerId.Text;$appSettings.sipServer=$sipServer.Text;$appSettings.sipUsername=$sipUser.Text;$appSettings.sipTransport=[string]$transport.SelectedItem;$appSettings.microphone=[string]$mic.SelectedItem;$appSettings.speaker=[string]$speaker.SelectedItem;$appSettings.productName=$product.Text;$appSettings.companyName=$company.Text;$appSettings.launchAtStartup=[bool]$startup.IsChecked;$appSettings.alwaysOnTopDuringCalls=[bool]$top.IsChecked
    $appSettings|ConvertTo-Json|Set-Content -LiteralPath $settingsPath -Encoding UTF8;$run="powershell.exe -NoProfile -ExecutionPolicy Bypass -STA -File `"$PSScriptRoot\CallBridge-Softphone.ps1`"";if($appSettings.launchAtStartup){New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'CallBridgeSoftphone' -Value $run -PropertyType String -Force|Out-Null}else{Remove-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'CallBridgeSoftphone' -ErrorAction SilentlyContinue};$window.Title="$($appSettings.productName) - $($appSettings.companyName)";(C 'BrandTitle').Text=$appSettings.productName.ToUpper();(C 'BrandSubtitle').Text=$appSettings.companyName.ToUpper();$status.Text='Settings saved and applied';Refresh-Connection
  })
  $form.Children.Add($left)|Out-Null;$form.Children.Add($right)|Out-Null;$content.Children.Add($form)|Out-Null
}
$search.Add_TextChanged({$q=$search.Text.ToLower();if([string]::IsNullOrWhiteSpace($q)){Render-Rows $script:currentRows}else{Render-Rows @($script:currentRows|Where-Object{$_.ToLower().Contains($q)} )}})
(C 'NavDashboard').Add_Click({Show-Dashboard})
(C 'NavPhone').Add_Click({Show-Phone})
(C 'NavContacts').Add_Click({Show-List 'Contacts' 'Search people, extensions, and queues' @('Maria Jensen|Available - (805) 555-0147|Call','Daniel Kim|In a call - (818) 555-0192|Call','Front Office|Available - Extension 200|Call','Support Queue|2 agents available - Extension 600|Call')})
(C 'NavHistory').Add_Click({Show-History})
(C 'NavMessages').Add_Click({Show-List 'Messages' 'Team conversations and SMS' @('Maria Jensen|Can you call me when available? - 2 min|Reply','Support Team|Queue coverage updated - 18 min|Open','Daniel Kim|Thank you for the quick help - 1 hr|Reply')})
(C 'NavVoicemail').Add_Click({Show-List 'Voicemail' 'New and saved voice messages' @('New voicemail|(805) 555-0122 - Today 1:08 PM - 00:42|Play','Saved voicemail|Simi Valley Dental Group - Yesterday - 01:14|Play')})
(C 'NavIntegrations').Add_Click({Show-List 'Connections' 'Phone services and account connections' @('Hosted voice service|Connection managed by your administrator|Status','SIP account|Registration provided automatically|Status','Desktop connector|127.0.0.1:8787|Test','Contact directory|Last sync Jul 11, 5:07 PM|Sync')})
(C 'NavSettings').Add_Click({Show-Settings})

foreach($button in (C 'DialPad').Children){$button.Add_Click({param($s,$e);$digit=([string]$s.Content).Substring(0,1);if($script:activeCallId){Post-Api "/telephony/calls/$script:activeCallId/dtmf" @{digits=$digit}|Out-Null}else{$number.Text += $digit}})}
(C 'FavoriteCall').Add_Click({$number.Text='(805) 555-0147';$callButton.RaiseEvent((New-Object Windows.RoutedEventArgs([Windows.Controls.Button]::ClickEvent)))})
$callButton.Add_Click({
  if([string]::IsNullOrWhiteSpace($number.Text)){return}
  if($script:activeCallId){Post-Api "/telephony/calls/$script:activeCallId/hangup"|Out-Null;$script:activeCallId=$null;$window.Topmost=$false;$callStatus.Text='READY TO CALL';$callButton.Content='CALL';$callButton.Background='#39C292';$number.IsReadOnly=$false;(C 'ActiveControls').Visibility='Collapsed'}
  else{$result=Post-Api '/telephony/calls' @{destination=$number.Text;callerId=$appSettings.extension};if($result -and $result.call){$script:activeCallId=$result.call.id;$window.Topmost=[bool]$appSettings.alwaysOnTopDuringCalls;$callStatus.Text='CONNECTED - TELEPHONY API';$callButton.Content='END CALL';$callButton.Background='#C95669';$number.IsReadOnly=$true;(C 'ActiveControls').Visibility='Visible'}else{[Windows.MessageBox]::Show('The telephony service is unavailable. Start CallBridge Internal v0.7 and try again.','CallBridge',[Windows.MessageBoxButton]::OK,[Windows.MessageBoxImage]::Warning)|Out-Null}}
})
(C 'MuteButton').Add_Click({if(!$script:activeCallId){return};$script:muted=!$script:muted;$r=Post-Api "/telephony/calls/$script:activeCallId/mute" @{muted=$script:muted};if($r){(C 'MuteButton').Content=if($script:muted){'Unmute'}else{'Mute'}}})
(C 'HoldButton').Add_Click({if(!$script:activeCallId){return};$action=if($script:held){'resume'}else{'hold'};$r=Post-Api "/telephony/calls/$script:activeCallId/$action";if($r){$script:held=!$script:held;(C 'HoldButton').Content=if($script:held){'Resume'}else{'Hold'};$callStatus.Text=if($script:held){'CALL ON HOLD'}else{'CONNECTED - TELEPHONY API'}}})
(C 'TransferButton').Add_Click({if(!$script:activeCallId){return};$destination=[Microsoft.VisualBasic.Interaction]::InputBox('Enter the extension or number to transfer this call to.','Transfer call','');if($destination){$r=Post-Api "/telephony/calls/$script:activeCallId/transfer" @{destination=$destination};if($r){$script:activeCallId=$null;$window.Topmost=$false;$callStatus.Text="TRANSFERRED TO $destination";$callButton.Content='CALL';$callButton.Background='#39C292';$number.IsReadOnly=$false;(C 'ActiveControls').Visibility='Collapsed'}}})
Refresh-Connection
$window.ShowDialog() | Out-Null



